### ISSUE TITLE
Google Service

### ISSUE THREAD

**Issue by DevTrinh** [justin0kg/VirtualApp2022#2]
Does it support google services?

**Comment by justin0kg** [comment]
yes

DevTrinh ***@***.***> 于2022年12月14日周三 17:21写道：

**Comment by justin0kg** [comment]
Yes, I can help you.

DevTrinh ***@***.***> 于2022年12月19日周一 17:55写道：

**Comment by justin0kg** [comment]
> please give me telegram or discord or something that can easily exchange information with you, thanks for your help. I'm a beginner, it's really hard for me
https://t.me/ZeusL404
